CREATE DATABASE ECOMMERCE;
GO

USE ECOMMERCE;

--CRIAR TABELA CLIENTE

CREATE TABLE CLIENT (
						ID_CLIENT INT IDENTITY PRIMARY KEY,
						FIRST_NAME VARCHAR(100),
						MIDDLE_NAME CHAR(3),
						LAST_NAME VARCHAR(100),
						CPF CHAR(11) NOT NULL,
						ADDRESS VARCHAR(100),

						CONSTRAINT UNIQUE_CPF_CLIENT UNIQUE (CPF)
						);


INSERT INTO CLIENT (FIRST_NAME,MIDDLE_NAME,LAST_NAME,CPF,ADDRESS) VALUES ('MARIA','M','SILVA',12345678901,'RUA SILVA DE PRATA - 29 - CARANGOLA - CIDADE DAS FLORES')
INSERT INTO CLIENT (FIRST_NAME,MIDDLE_NAME,LAST_NAME,CPF,ADDRESS) VALUES ('MATHEUS','O','PIMENTEL',987654321,'RUA ALAMEDA - 289 - CENTRO - CIDADE DAS FLORES')
INSERT INTO CLIENT (FIRST_NAME,MIDDLE_NAME,LAST_NAME,CPF,ADDRESS) VALUES ('RICARDO','F','SILVA',1905784681,'RUA MARIA AGUIAR - 125 - TANCHAL - OURO PEQUENO')
INSERT INTO CLIENT (FIRST_NAME,MIDDLE_NAME,LAST_NAME,CPF,ADDRESS) VALUES ('JULIA','S','FRANÇA',3945708654,'RUA MAO ARMADA - 75 - LAPA - CIDADE DE DEUS')
INSERT INTO CLIENT (FIRST_NAME,MIDDLE_NAME,LAST_NAME,CPF,ADDRESS) VALUES ('ROBERTA','G','ASSIS',9509728632,'RUA ELEGANTE - 99 - AIE - ´JABILEU')
INSERT INTO CLIENT (FIRST_NAME,MIDDLE_NAME,LAST_NAME,CPF,ADDRESS) VALUES ('ISABELA','M','CRUZ',45424514655,'RUA ALAMEDA - 289 - CENTRO - CIDADE DAS FLORES')



--CRIAR TABELA PRODUTO
--SIZE = DIMENSÃO DO PRODUTO

CREATE TABLE PRODUCT (
						ID_PRODUCT INT IDENTITY PRIMARY KEY,
						PRODUCT_NAME VARCHAR(100) NOT NULL,
						CLASSIFICATION_KIDS BIT DEFAULT 0,
						CATEGORY VARCHAR(100) NOT NULL CHECK (CATEGORY IN('ELETRÔNICO','VESTIMENTA','BRINQUEDOS','ALIMENTOS','MÓVEIS')),
						RATING FLOAT DEFAULT 0,
						SIZE VARCHAR(10)
						);


INSERT INTO PRODUCT (PRODUCT_NAME, CLASSIFICATION_KIDS, CATEGORY, RATING, SIZE) VALUES ('FONE DE OUVIDO',0,'ELETRÔNICO',4,NULL)
INSERT INTO PRODUCT (PRODUCT_NAME, CLASSIFICATION_KIDS, CATEGORY, RATING, SIZE) VALUES ('BARBIE ELSA',1,'BRINQUEDOS',3,NULL)
INSERT INTO PRODUCT (PRODUCT_NAME, CLASSIFICATION_KIDS, CATEGORY, RATING, SIZE) VALUES ('BODY CARTERS',1,'VESTIMENTA',5,NULL)
INSERT INTO PRODUCT (PRODUCT_NAME, CLASSIFICATION_KIDS, CATEGORY, RATING, SIZE) VALUES ('MICROFONE VEDO - YOUTUBER',0,'ELETRÔNICO',4,NULL)
INSERT INTO PRODUCT (PRODUCT_NAME, CLASSIFICATION_KIDS, CATEGORY, RATING, SIZE) VALUES ('SOFÁ RETRÁTIL',0,'MÓVEIS',3,'3X57X80')
INSERT INTO PRODUCT (PRODUCT_NAME, CLASSIFICATION_KIDS, CATEGORY, RATING, SIZE) VALUES ('FARINHA DE ARROZ',0,'ALIMENTOS',2,NULL)
INSERT INTO PRODUCT (PRODUCT_NAME, CLASSIFICATION_KIDS, CATEGORY, RATING, SIZE) VALUES ('FIRE STICK AMAZON',0,'ELETRÔNICO',3,NULL)

--CRIAR TABELA PEDIDO


CREATE TABLE ORDERS (
						ID_ORDER INT IDENTITY PRIMARY KEY,
						ID_ORDER_CLIENT INT,
						ORDER_STATUS VARCHAR(100) CHECK (ORDER_STATUS IN('CANCELADO','CONFIRMADO','EM_PROCESSAMENTO')) DEFAULT 'EM_PROCESSAMENTO',
						ORDER_DESCRIPTION VARCHAR(255),
						SHIPMENT FLOAT DEFAULT 10,
						PAYMENT_CASH BIT DEFAULT 0,
						CONSTRAINT FK_ORDERS_CLIENT FOREIGN KEY (ID_ORDER_CLIENT) REFERENCES CLIENT(ID_CLIENT)
						);

INSERT INTO ORDERS (ID_ORDER_CLIENT,ORDER_STATUS,ORDER_DESCRIPTION,SHIPMENT,PAYMENT_CASH) VALUES (1,NULL,'COMPRA VIA APLICATIVO',NULL,1)
INSERT INTO ORDERS (ID_ORDER_CLIENT,ORDER_STATUS,ORDER_DESCRIPTION,SHIPMENT,PAYMENT_CASH) VALUES (2,NULL,'COMPRA VIA APLICATIVO',50,0)
INSERT INTO ORDERS (ID_ORDER_CLIENT,ORDER_STATUS,ORDER_DESCRIPTION,SHIPMENT,PAYMENT_CASH) VALUES (3,'CONFIRMADO',NULL,NULL,1)
INSERT INTO ORDERS (ID_ORDER_CLIENT,ORDER_STATUS,ORDER_DESCRIPTION,SHIPMENT,PAYMENT_CASH) VALUES (4,NULL,'COMPRA VIA WEB SITE',150,0)


--PARA SER CONTINUADO NO DESAFIO: TERMINE DE IMPLEMENTAR A TABELA E CRIE A CONEXÃO COM AS TABELAS NECESSÁRIAS
--ALÉM DISSO, REFLITA ESSA MODIFICAÇÃO NO DIAGRAMA DE ESQUEMA RELACIONAL
--CRIAR CONSTRAINTS RELACIONADA AO PAGAMENTO

CREATE TABLE PAYMENT (
						ID_CLIENT INT,
						ID_PAYMENT INT,
						TYPE_PAYMENT VARCHAR(100) CHECK(TYPE_PAYMENT IN('BOLETO','CARTÃO','DOIS CARTÕES')),
						LIMIT_AVAILABLE FLOAT,
						PRIMARY KEY (ID_CLIENT, ID_PAYMENT)
						);


CREATE TABLE PAYMENT_CARD (
							ID_CARD INT IDENTITY PRIMARY KEY,
							NUM_CARD VARCHAR (16) NOT NULL,
							VALID CHAR(4),
							CARD_NAME VARCHAR(100),
							
							)



--CRIAR TABELA ESTOQUE
CREATE TABLE PRODUCT_STORAGE(
								ID_PROD_STORAGE INT IDENTITY PRIMARY KEY,
								STORAGE_LOCATION VARCHAR(255),
								QUANTITY INT DEFAULT 10
								);

INSERT INTO PRODUCT_STORAGE (STORAGE_LOCATION, QUANTITY) VALUES ('RIO DE JANEIRO', 1000)
INSERT INTO PRODUCT_STORAGE (STORAGE_LOCATION, QUANTITY) VALUES ('RIO DE JANEIRO', 500)
INSERT INTO PRODUCT_STORAGE (STORAGE_LOCATION, QUANTITY) VALUES ('SAO PAULO', 10)
INSERT INTO PRODUCT_STORAGE (STORAGE_LOCATION, QUANTITY) VALUES ('SAO PAULO', 100)
INSERT INTO PRODUCT_STORAGE (STORAGE_LOCATION, QUANTITY) VALUES ('SAO PAULO', 10)
INSERT INTO PRODUCT_STORAGE (STORAGE_LOCATION, QUANTITY) VALUES ('BRASILIA', 60)

--CRIAR TABELA FORNECEDOR

CREATE TABLE SUPPLIER (
						ID_SUPPLIER INT IDENTITY PRIMARY KEY,
						SOCIAL_NAME VARCHAR(255) NOT NULL,
						CNPJ CHAR(14) NOT NULL,
						CONTACT CHAR(11) NOT NULL,
						CONSTRAINT UNIQUE_CNPJ_SUPPLIER UNIQUE (CNPJ)
						);

INSERT INTO SUPPLIER (SOCIAL_NAME,CNPJ,CONTACT) VALUES ('ALMEIDA E FILHOS',12345678901234,'11123456789')
INSERT INTO SUPPLIER (SOCIAL_NAME,CNPJ,CONTACT) VALUES ('RICARDO ELETRO',42394082648562,'12353453464')
INSERT INTO SUPPLIER (SOCIAL_NAME,CNPJ,CONTACT) VALUES ('ELETRONICO VALMA',93074029490623,'21346463645')


--CRIAR TABELA VENDEDOR

CREATE TABLE SELLER (
						ID_SELLER INT IDENTITY PRIMARY KEY,
						SOCIAL_NAME VARCHAR(255) NOT NULL,
						ABSTRACT_NAME VARCHAR(255),
						CNPJ CHAR(14),
						CPF CHAR(11),
						LOCATION VARCHAR(255),
						CONTACT CHAR(11) NOT NULL,
						CONSTRAINT UNIQUE_CNPJ_SELLER UNIQUE (CNPJ),
						CONSTRAINT UNIQUE_CPF_SELLER UNIQUE (CPF),
						CONSTRAINT UNIQUE_SOCIAL_NAME_SELLER UNIQUE (SOCIAL_NAME)
						);

INSERT INTO SELLER (SOCIAL_NAME, ABSTRACT_NAME, CNPJ, CPF, LOCATION, CONTACT) VALUES ('TECH ELETRONICS', NULL, 12345678901234, NULL, 'RIO DE JANEIRO', '21994628745')
INSERT INTO SELLER (SOCIAL_NAME, ABSTRACT_NAME, CNPJ, CPF, LOCATION, CONTACT) VALUES ('BOTIQUE DRUGAS', NULL, NULL, 12345678901, 'RIO DE JANEIRO', '12342342351')
INSERT INTO SELLER (SOCIAL_NAME, ABSTRACT_NAME, CNPJ, CPF, LOCATION, CONTACT) VALUES ('KIDS WORLD', NULL, 53986052834650, NULL, 'SAO PAULO', '11435235466')



--CRIAR TABELA PRODUTO_VENDEDOR

CREATE TABLE PRODUCT_SELLER (
								ID_P_SELLER INT,
								ID_P_PRODUCT INT,
								PROD_QUANTITY INT DEFAULT 1,
								PRIMARY KEY (ID_P_SELLER, ID_P_PRODUCT),
								CONSTRAINT FK_PRODUCT_SELLER FOREIGN KEY (ID_P_SELLER) REFERENCES SELLER (ID_SELLER),
								CONSTRAINT FK_PRODUCT_PRODUCT FOREIGN KEY (ID_P_PRODUCT) REFERENCES PRODUCT (ID_PRODUCT)
);

INSERT INTO PRODUCT_SELLER (ID_P_SELLER, ID_P_PRODUCT, PROD_QUANTITY) VALUES (1,6,80)
INSERT INTO PRODUCT_SELLER (ID_P_SELLER, ID_P_PRODUCT, PROD_QUANTITY) VALUES (2,7,10)


--CRIAR TABELA PRODUTO_ORDEM

CREATE TABLE PRODUCT_ORDER (
								ID_PO_PRODUCT INT,
								ID_PO_ORDER INT,
								PO_QUANTITY INT DEFAULT 1,
								PO_STATUS VARCHAR(100) CHECK (PO_STATUS IN('DISPONÍVEL','SEM_ESTOQUE')) DEFAULT 'DISPONÍVEL',
								PRIMARY KEY (ID_PO_PRODUCT,ID_PO_ORDER),
								CONSTRAINT FK_PO_PRODUCT_SELLER FOREIGN KEY (ID_PO_PRODUCT) REFERENCES PRODUCT (ID_PRODUCT),
								CONSTRAINT FK_PO_PRODUCT_PRODUCT FOREIGN KEY (ID_PO_ORDER) REFERENCES ORDERS (ID_ORDER)
								)

INSERT INTO PRODUCT_ORDER (ID_PO_PRODUCT, ID_PO_ORDER, PO_QUANTITY, PO_STATUS) VALUES (1,1,2,NULL)
INSERT INTO PRODUCT_ORDER (ID_PO_PRODUCT, ID_PO_ORDER, PO_QUANTITY, PO_STATUS) VALUES (2,1,1,NULL)
INSERT INTO PRODUCT_ORDER (ID_PO_PRODUCT, ID_PO_ORDER, PO_QUANTITY, PO_STATUS) VALUES (3,2,1,NULL)


--CRIAR TABELA ESTOQUE_LOCAL

CREATE TABLE STORAGE_LOCATION (
								ID_LOC_PRODUCT INT,
								ID_LOC_STORAGE INT,
								LOCATION VARCHAR(255) NOT NULL,
								PRIMARY KEY (ID_LOC_PRODUCT, ID_LOC_STORAGE),
								CONSTRAINT FK_LOC_PRODUCT_SELLER FOREIGN KEY (ID_LOC_PRODUCT) REFERENCES PRODUCT (ID_PRODUCT),
								CONSTRAINT FK_LOC_PRODUCT_PRODUCT FOREIGN KEY (ID_LOC_STORAGE) REFERENCES ORDERS (ID_ORDER)
								)

INSERT INTO STORAGE_LOCATION (ID_LOC_PRODUCT,ID_LOC_STORAGE,LOCATION) VALUES (1,2,'RJ')
INSERT INTO STORAGE_LOCATION (ID_LOC_PRODUCT,ID_LOC_STORAGE,LOCATION) VALUES (2,4,'GO')


--CRIAR TABELA PRODUCT_FORNECEDOR
CREATE TABLE PRODUCT_SUPPLIER (
								ID_PS_SUPPLIER INT,
								ID_PS_PRODUCT INT,
								QUANTITY INT NOT NULL,
								PRIMARY KEY (ID_PS_SUPPLIER, ID_PS_PRODUCT),
								CONSTRAINT FK_PRODUCT_SUPPLIER_SUPPLIER FOREIGN KEY (ID_PS_SUPPLIER) REFERENCES SUPPLIER (ID_SUPPLIER),
								CONSTRAINT FK_PRODUCT_SUPPLIER_PRODUCT FOREIGN KEY (ID_PS_PRODUCT) REFERENCES PRODUCT(ID_PRODUCT)
)

INSERT INTO PRODUCT_SUPPLIER (ID_PS_SUPPLIER, ID_PS_PRODUCT, QUANTITY) VALUES (1,1,500)
INSERT INTO PRODUCT_SUPPLIER (ID_PS_SUPPLIER, ID_PS_PRODUCT, QUANTITY) VALUES (1,2,400)
INSERT INTO PRODUCT_SUPPLIER (ID_PS_SUPPLIER, ID_PS_PRODUCT, QUANTITY) VALUES (2,4,633)
INSERT INTO PRODUCT_SUPPLIER (ID_PS_SUPPLIER, ID_PS_PRODUCT, QUANTITY) VALUES (3,4,5)
INSERT INTO PRODUCT_SUPPLIER (ID_PS_SUPPLIER, ID_PS_PRODUCT, QUANTITY) VALUES (2,5,10)



------------------------ QUERYS -----------------------------------------------


SELECT *
FROM CLIENT C
INNER JOIN ORDERS O ON C.ID_CLIENT = O.ID_ORDER_CLIENT
INNER JOIN PRODUCT_ORDER PO ON PO.ID_PO_ORDER = O.ID_ORDER


SELECT CONCAT(FIRST_NAME,' ',LAST_NAME), O.*FROM CLIENT C
INNER JOIN ORDERS O ON C.ID_CLIENT = O.ID_ORDER_CLIENT
